// This file is auto-generated by scripts/sync-db.mjs
// DO NOT EDIT MANUALLY
export const snapshot: any = {
  "gallery": [],
  "menuCategories": [
    {
      "_creationTime": 1777551933008.462,
      "_id": "jh78cwsewcbdw658mm22jn1djn85tdbp",
      "active": true,
      "displayOrder": 0,
      "name": "Pizzas Base Tomate",
      "slug": "pizzas-base-tomate"
    },
    {
      "_creationTime": 1777551933008.4622,
      "_id": "jh782kxpd2rv5kdv12929vqwnd85vexm",
      "active": true,
      "displayOrder": 1,
      "name": "Pizzas Base Crème",
      "slug": "pizzas-base-creme"
    },
    {
      "_creationTime": 1777551933008.4624,
      "_id": "jh77e5xx9sdptqp3s2fw8d8w1d85v67d",
      "active": true,
      "displayOrder": 2,
      "name": "Pizzas Spéciales",
      "slug": "pizzas-speciales"
    },
    {
      "_creationTime": 1777551933008.4626,
      "_id": "jh77s66p3rmyd5qrfnf72bcb9n85v1fb",
      "active": true,
      "displayOrder": 3,
      "name": "Paninis",
      "slug": "paninis"
    },
    {
      "_creationTime": 1777551933008.463,
      "_id": "jh76vagwt3v4my1kxapp9zs1td85ttzx",
      "active": true,
      "displayOrder": 4,
      "name": "Burgers",
      "slug": "burgers"
    },
    {
      "_creationTime": 1777551933008.4631,
      "_id": "jh74pvamwe8tt7r6ss2fabby4985vddn",
      "active": true,
      "displayOrder": 5,
      "name": "Tacos",
      "slug": "tacos"
    },
    {
      "_creationTime": 1777551933008.4634,
      "_id": "jh76cm0nwneregg608g62vn2wd85vrfa",
      "active": true,
      "displayOrder": 6,
      "name": "Tex-Mex",
      "slug": "tex-mex"
    },
    {
      "_creationTime": 1777551933008.4636,
      "_id": "jh742p6tgg2245bfpkddq50s2h85tpg6",
      "active": true,
      "displayOrder": 7,
      "name": "Salades",
      "slug": "salades"
    },
    {
      "_creationTime": 1777551933008.4639,
      "_id": "jh793hhekrymhn7ewrem7r0hcs85v5p4",
      "active": true,
      "displayOrder": 8,
      "name": "Desserts",
      "slug": "desserts"
    },
    {
      "_creationTime": 1777551933008.464,
      "_id": "jh7eqybcjg8p31ae8xyt1mq8y985vj10",
      "active": true,
      "displayOrder": 9,
      "name": "Boissons",
      "slug": "boissons"
    }
  ],
  "menuItemToppings": [
    {
      "_creationTime": 1777551933008.494,
      "_id": "jn758n8v83w1598tk63eh3j73585tmkb",
      "displayOrder": 0,
      "menuItemId": "js79w64j5amewk3tspzmmee6ph85vt17",
      "toppingCategoryId": "taille"
    },
    {
      "_creationTime": 1777551933008.4941,
      "_id": "jn75xx303tx409y6vgat18bgws85vktn",
      "displayOrder": 1,
      "menuItemId": "js79w64j5amewk3tspzmmee6ph85vt17",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1777551933008.4944,
      "_id": "jn7b44m5jjjrstvf9pqyfqtcv585vqs3",
      "displayOrder": 0,
      "menuItemId": "js7abq1n5y3s0che5nrstmgtr585tndw",
      "toppingCategoryId": "taille"
    },
    {
      "_creationTime": 1777551933008.4946,
      "_id": "jn78hb0ws7ypqsjmd3ab99ydbh85t2sa",
      "displayOrder": 1,
      "menuItemId": "js7abq1n5y3s0che5nrstmgtr585tndw",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1777551933008.4949,
      "_id": "jn73jxk8d01e9rzdwxtb08bh8n85v9za",
      "displayOrder": 0,
      "menuItemId": "js72z9ygsr4985dr46853pvtrd85v252",
      "toppingCategoryId": "taille"
    },
    {
      "_creationTime": 1777551933008.495,
      "_id": "jn761x4ge874gkvm8xxwdd28zd85tzjk",
      "displayOrder": 1,
      "menuItemId": "js72z9ygsr4985dr46853pvtrd85v252",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1777551933008.4954,
      "_id": "jn70p28r2na55n5ryd5q2t5whs85ts30",
      "displayOrder": 0,
      "menuItemId": "js7275dmyb6hydwxpqj5h1mg7n85vwz9",
      "toppingCategoryId": "taille"
    },
    {
      "_creationTime": 1777551933008.4956,
      "_id": "jn79r5tasync7p92er09a397zd85vzje",
      "displayOrder": 1,
      "menuItemId": "js7275dmyb6hydwxpqj5h1mg7n85vwz9",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1777551933008.4958,
      "_id": "jn738b9cttnfd0pvj4x745qpbs85v5t9",
      "displayOrder": 0,
      "menuItemId": "js7e41xxwxr5tyjs0qrc3v3dr985v3t9",
      "toppingCategoryId": "taille"
    },
    {
      "_creationTime": 1777551933008.496,
      "_id": "jn78w9mqes8mynbgp04f3qdf5s85t6b7",
      "displayOrder": 1,
      "menuItemId": "js7e41xxwxr5tyjs0qrc3v3dr985v3t9",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1777551933008.4963,
      "_id": "jn78zet5b9njshv7hjsdbcnv0s85vh73",
      "displayOrder": 0,
      "menuItemId": "js71wqenc0nxxjm44zzzrc3vtd85te0m",
      "toppingCategoryId": "taille"
    },
    {
      "_creationTime": 1777551933008.4966,
      "_id": "jn79endec4njfmksqmhhq1xg8d85v7aj",
      "displayOrder": 1,
      "menuItemId": "js71wqenc0nxxjm44zzzrc3vtd85te0m",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1777551933008.4968,
      "_id": "jn7ccerek25x0z99mzdjvg7tqn85tqpz",
      "displayOrder": 0,
      "menuItemId": "js72w2ahfxc709r9hty4zm43z185tx1r",
      "toppingCategoryId": "taille"
    },
    {
      "_creationTime": 1777551933008.497,
      "_id": "jn79f0vmx37bmvrg7z1secc35d85v1e7",
      "displayOrder": 1,
      "menuItemId": "js72w2ahfxc709r9hty4zm43z185tx1r",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1777551933008.4973,
      "_id": "jn7016e4yj2dnnkhs535x5mmx585t1qt",
      "displayOrder": 0,
      "menuItemId": "js78y0gkah4gtnksamr2y84nhd85v8jj",
      "toppingCategoryId": "taille"
    },
    {
      "_creationTime": 1777551933008.4976,
      "_id": "jn7cvsm2nhs84gzefdc5gmpwqh85vasz",
      "displayOrder": 1,
      "menuItemId": "js78y0gkah4gtnksamr2y84nhd85v8jj",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1777551933008.4978,
      "_id": "jn77an7pwb489fyc7jdkxg2e2n85tg25",
      "displayOrder": 0,
      "menuItemId": "js70f4hh612ffkf4cvek6xd5dh85twsm",
      "toppingCategoryId": "taille"
    },
    {
      "_creationTime": 1777551933008.498,
      "_id": "jn798wwmyy4z405ex13024qdv985tmr1",
      "displayOrder": 1,
      "menuItemId": "js70f4hh612ffkf4cvek6xd5dh85twsm",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1777551933008.4983,
      "_id": "jn7378tdt42d3qw72zjk98s0nx85tre4",
      "displayOrder": 0,
      "menuItemId": "js72y0vy0bdf7trtp8d0awtxe185t9qt",
      "toppingCategoryId": "taille"
    },
    {
      "_creationTime": 1777551933008.4985,
      "_id": "jn73y6kp6jb98ngbqxgcr1ahan85vd0j",
      "displayOrder": 1,
      "menuItemId": "js72y0vy0bdf7trtp8d0awtxe185t9qt",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1777551933008.4988,
      "_id": "jn7a62fnz1r7mwhtq41zwpf0md85tnad",
      "displayOrder": 0,
      "menuItemId": "js744c0c9rn8fzn3r2evm13qm185vr98",
      "toppingCategoryId": "taille"
    },
    {
      "_creationTime": 1777551933008.499,
      "_id": "jn7f546q06pd9c5ejepce3j7jx85vejb",
      "displayOrder": 1,
      "menuItemId": "js744c0c9rn8fzn3r2evm13qm185vr98",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1777551933008.4993,
      "_id": "jn7cwc841jxewhmf0wybyh6nzs85tdf5",
      "displayOrder": 0,
      "menuItemId": "js7fsyqrb15atnp25tnhr5bwp985t7ke",
      "toppingCategoryId": "taille"
    },
    {
      "_creationTime": 1777551933008.4995,
      "_id": "jn74v3q57t75qk9et2zqm41qa585t4tr",
      "displayOrder": 1,
      "menuItemId": "js7fsyqrb15atnp25tnhr5bwp985t7ke",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1777551933008.4998,
      "_id": "jn7a22q6emwc7zpg466h32fw0n85va02",
      "displayOrder": 0,
      "menuItemId": "js75gn99r1n3y82954fpj8pxa985tets",
      "toppingCategoryId": "taille"
    },
    {
      "_creationTime": 1777551933008.5,
      "_id": "jn7efa3z3z70m5gh4zz5dmppvd85vehe",
      "displayOrder": 1,
      "menuItemId": "js75gn99r1n3y82954fpj8pxa985tets",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1777551933008.5002,
      "_id": "jn7dbzxpq7yrp3hk76c9q34pp185vph1",
      "displayOrder": 0,
      "menuItemId": "js74ndw8ngjaz77w39jm0vxej185v78b",
      "toppingCategoryId": "taille"
    },
    {
      "_creationTime": 1777551933008.5005,
      "_id": "jn7bfh5mc4vnycmd5e59ga5sx985v380",
      "displayOrder": 1,
      "menuItemId": "js74ndw8ngjaz77w39jm0vxej185v78b",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1777551933008.5007,
      "_id": "jn7e10m8h1psnxfbcbsdamd8gn85v44t",
      "displayOrder": 0,
      "menuItemId": "js753af4aymen8g0s9m3xbwywx85v7g7",
      "toppingCategoryId": "taille"
    },
    {
      "_creationTime": 1777551933008.501,
      "_id": "jn7dqp9bgqpddmejtccjptv3gs85vh3k",
      "displayOrder": 1,
      "menuItemId": "js753af4aymen8g0s9m3xbwywx85v7g7",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1777551933008.5012,
      "_id": "jn76sw1txh8krsdbv0beyzhhy585tb7k",
      "displayOrder": 0,
      "menuItemId": "js7aqpsya18sgq82t4k3k3a39n85tejm",
      "toppingCategoryId": "taille"
    },
    {
      "_creationTime": 1777551933008.5015,
      "_id": "jn70vx3gv2n3enbsv2ndhey8xh85tme2",
      "displayOrder": 1,
      "menuItemId": "js7aqpsya18sgq82t4k3k3a39n85tejm",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1777551933008.5017,
      "_id": "jn7fyyyxycwh2q1try1bfssfa985t8m5",
      "displayOrder": 0,
      "menuItemId": "js7a0tzr2a1azrnehr9dkhhaqh85v363",
      "toppingCategoryId": "taille"
    },
    {
      "_creationTime": 1777551933008.502,
      "_id": "jn7adawngtr4bq2mvb3pe12jdx85vvgn",
      "displayOrder": 1,
      "menuItemId": "js7a0tzr2a1azrnehr9dkhhaqh85v363",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1777551933008.5022,
      "_id": "jn7bzspa36b0wfkn984wgx9kts85t231",
      "displayOrder": 0,
      "menuItemId": "js79nwmgyxnwzdk1jh4yc3khp585vt3y",
      "toppingCategoryId": "taille"
    },
    {
      "_creationTime": 1777551933008.5024,
      "_id": "jn71y78z0q388rmx9jx0zt7xfn85vc2b",
      "displayOrder": 1,
      "menuItemId": "js79nwmgyxnwzdk1jh4yc3khp585vt3y",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1777551933008.5027,
      "_id": "jn7egwz229c4srcb61nqsd5p1x85tzrq",
      "displayOrder": 0,
      "menuItemId": "js74q4d7a4fk6rpzbqnqzy6gds85vx96",
      "toppingCategoryId": "taille"
    },
    {
      "_creationTime": 1777551933008.503,
      "_id": "jn73gfkbhnrqx5e6mm2snszd5x85v3zk",
      "displayOrder": 1,
      "menuItemId": "js74q4d7a4fk6rpzbqnqzy6gds85vx96",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1777551933008.5032,
      "_id": "jn70bcy8vghqmtbtkn9kkac92585vp7v",
      "displayOrder": 0,
      "menuItemId": "js7cza3eh3vcv6gc31fmdvz2t985vhyr",
      "toppingCategoryId": "taille"
    },
    {
      "_creationTime": 1777551933008.5034,
      "_id": "jn78edkeej7whd1q6xwhw2bgrh85tz2y",
      "displayOrder": 1,
      "menuItemId": "js7cza3eh3vcv6gc31fmdvz2t985vhyr",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1777551933008.5037,
      "_id": "jn7d60y7z5eba14fv6zdqnzw7x85tkpb",
      "displayOrder": 0,
      "menuItemId": "js7es63xtqv650d7m5kqbzcsb985tn57",
      "toppingCategoryId": "taille"
    },
    {
      "_creationTime": 1777551933008.504,
      "_id": "jn7ev5f50r8me3xpx0wzyebmqs85v9e9",
      "displayOrder": 1,
      "menuItemId": "js7es63xtqv650d7m5kqbzcsb985tn57",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1777551933008.5042,
      "_id": "jn7fehdjxnenqs5e5ndv98vvjh85v8s4",
      "displayOrder": 0,
      "menuItemId": "js739aaeq7j2mhztfm2657gs9d85vaa0",
      "toppingCategoryId": "taille"
    },
    {
      "_creationTime": 1777551933008.5044,
      "_id": "jn70aaaxzwetez5d77xtvb1tcs85td04",
      "displayOrder": 1,
      "menuItemId": "js739aaeq7j2mhztfm2657gs9d85vaa0",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1777551933008.5046,
      "_id": "jn79eqr2b19s250mk15v1z8t4d85vec4",
      "displayOrder": 0,
      "menuItemId": "js7406gtm5wa09gzhepw7pmzwd85tpqn",
      "toppingCategoryId": "taille"
    },
    {
      "_creationTime": 1777551933008.505,
      "_id": "jn77k1c4vkx69sey117vr6av2d85va8v",
      "displayOrder": 1,
      "menuItemId": "js7406gtm5wa09gzhepw7pmzwd85tpqn",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1777551933008.5051,
      "_id": "jn72akgxm1r0m3n040z1s707ed85ty7j",
      "displayOrder": 0,
      "menuItemId": "js77shftwn80ea7q21vhhdkra585thad",
      "toppingCategoryId": "taille"
    },
    {
      "_creationTime": 1777551933008.5054,
      "_id": "jn709tdqz68nnkgrs3ayve7vy585tb5s",
      "displayOrder": 1,
      "menuItemId": "js77shftwn80ea7q21vhhdkra585thad",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1777551933008.5056,
      "_id": "jn7e3tq36mrfdvpk2zwdn32rrs85vv8s",
      "displayOrder": 0,
      "menuItemId": "js76g8w71tq876qa1jcyq0x3n585vhca",
      "toppingCategoryId": "taille"
    },
    {
      "_creationTime": 1777551933008.5059,
      "_id": "jn78eejsgq5vh5gm9bgb1rdtj985trx9",
      "displayOrder": 1,
      "menuItemId": "js76g8w71tq876qa1jcyq0x3n585vhca",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1777551933008.506,
      "_id": "jn73faahaka8g3wmjfhwvx8fq185t4r8",
      "displayOrder": 0,
      "menuItemId": "js7bea2y0rzbq2at41nke4tcr585v4kf",
      "toppingCategoryId": "taille"
    },
    {
      "_creationTime": 1777551933008.5063,
      "_id": "jn739yr1wg0weybgktg14p4khx85t7zc",
      "displayOrder": 1,
      "menuItemId": "js7bea2y0rzbq2at41nke4tcr585v4kf",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1777551933008.5066,
      "_id": "jn7075xe2by1rgrzaz24dngcfd85t8jw",
      "displayOrder": 0,
      "menuItemId": "js7afqjaheervy5rk7r7zdsr4n85vr8b",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1777551933008.5068,
      "_id": "jn70p052qvcc2nce0s2hvv1p5985tat5",
      "displayOrder": 1,
      "menuItemId": "js7afqjaheervy5rk7r7zdsr4n85vr8b",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1777551933008.507,
      "_id": "jn7c7kymp79vgs8a0ttwqe9c7185th3x",
      "displayOrder": 2,
      "menuItemId": "js7afqjaheervy5rk7r7zdsr4n85vr8b",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1777551933008.5073,
      "_id": "jn74n09fhpakd4tvm11zq2a5qh85te3t",
      "displayOrder": 0,
      "menuItemId": "js7df4ndmhr4pqm9jz5rpchsan85v6ps",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1777551933008.5076,
      "_id": "jn7cnfhxacsqnz2hnc16tr1kqh85t2rv",
      "displayOrder": 1,
      "menuItemId": "js7df4ndmhr4pqm9jz5rpchsan85v6ps",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1777551933008.5078,
      "_id": "jn7cs0bp8cpbdyvb9qhd19qb7x85vbaz",
      "displayOrder": 2,
      "menuItemId": "js7df4ndmhr4pqm9jz5rpchsan85v6ps",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1777551933008.508,
      "_id": "jn7eeepv0y11508w91dgtq8yax85thgd",
      "displayOrder": 0,
      "menuItemId": "js70w40r3825maccj5e5w1jc5n85vfpj",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1777551933008.5083,
      "_id": "jn76jf41tsmba0x16wr012mvq185v4b1",
      "displayOrder": 1,
      "menuItemId": "js70w40r3825maccj5e5w1jc5n85vfpj",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1777551933008.5085,
      "_id": "jn7ceevs619eqs3t6ma8zmmn3s85tcrh",
      "displayOrder": 2,
      "menuItemId": "js70w40r3825maccj5e5w1jc5n85vfpj",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1777551933008.5088,
      "_id": "jn7frs08h3sghkfkdzxh73gk0x85tr6g",
      "displayOrder": 0,
      "menuItemId": "js7577zpzejze0qb4the74w2qx85tz1f",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1777551933008.509,
      "_id": "jn724g9712enekdhp9wdwqzw6985vaez",
      "displayOrder": 1,
      "menuItemId": "js7577zpzejze0qb4the74w2qx85tz1f",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1777551933008.5093,
      "_id": "jn733znk2pp1dp6msz0gneq71185te59",
      "displayOrder": 2,
      "menuItemId": "js7577zpzejze0qb4the74w2qx85tz1f",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1777551933008.5095,
      "_id": "jn7dsk3ex93veha9veb6h32en185txr1",
      "displayOrder": 0,
      "menuItemId": "js75n3cv0aqc8s4bh0wwtc9tcd85vmhg",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1777551933008.5098,
      "_id": "jn7e3fvdj0rfzhjav397x3hwjn85vwwy",
      "displayOrder": 1,
      "menuItemId": "js75n3cv0aqc8s4bh0wwtc9tcd85vmhg",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1777551933008.51,
      "_id": "jn7ehcj8e7fk0pty0bhbhnfcmd85vazg",
      "displayOrder": 2,
      "menuItemId": "js75n3cv0aqc8s4bh0wwtc9tcd85vmhg",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1777551933008.5103,
      "_id": "jn77pxegg5sbx7c15ak9wqtcg985vek9",
      "displayOrder": 0,
      "menuItemId": "js7e53b5wqgkn3p05d342t1bh185v05b",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1777551933008.5105,
      "_id": "jn7f9v20cfhvdkx835bnx81kvn85v8cm",
      "displayOrder": 1,
      "menuItemId": "js7e53b5wqgkn3p05d342t1bh185v05b",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1777551933008.5107,
      "_id": "jn7edrh9w4639hr3xtqds9cwz585t7m9",
      "displayOrder": 2,
      "menuItemId": "js7e53b5wqgkn3p05d342t1bh185v05b",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1777551933008.511,
      "_id": "jn717bp2v0nemx0rg9rhz0czfd85te2m",
      "displayOrder": 0,
      "menuItemId": "js7fs3ewptbhczy5d67r6tew8x85v93y",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1777551933008.5112,
      "_id": "jn73e024rgderf83427csqfyvh85thh1",
      "displayOrder": 1,
      "menuItemId": "js7fs3ewptbhczy5d67r6tew8x85v93y",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1777551933008.5115,
      "_id": "jn71c96ac92jrf1tp8sx94z95n85tfx0",
      "displayOrder": 2,
      "menuItemId": "js7fs3ewptbhczy5d67r6tew8x85v93y",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1777551933008.5117,
      "_id": "jn7cn9pkxh1pb4jf5p1ztbtvt585tm1g",
      "displayOrder": 0,
      "menuItemId": "js70v78fcwr48pqtewz3x53pan85vjyt",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1777551933008.512,
      "_id": "jn70br3w9r135evvdw9rz1myjh85twpv",
      "displayOrder": 1,
      "menuItemId": "js70v78fcwr48pqtewz3x53pan85vjyt",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1777551933008.5122,
      "_id": "jn7dy2tm6v36g1nt9p1rf6et2n85vmf1",
      "displayOrder": 2,
      "menuItemId": "js70v78fcwr48pqtewz3x53pan85vjyt",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1777551933008.5125,
      "_id": "jn7d2rn83yae776a7b83vcas9x85t1yd",
      "displayOrder": 0,
      "menuItemId": "js73zp2qp2bgbkg7rnhhw3m16d85ta0b",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1777551933008.5127,
      "_id": "jn7f9pksvwvgm39dr78pszdd7n85t5jr",
      "displayOrder": 1,
      "menuItemId": "js73zp2qp2bgbkg7rnhhw3m16d85ta0b",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1777551933008.513,
      "_id": "jn77mgarne6e5swst7rayqwgbs85vyd7",
      "displayOrder": 2,
      "menuItemId": "js73zp2qp2bgbkg7rnhhw3m16d85ta0b",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1777551933008.5132,
      "_id": "jn7261kpxz6v5jt091z2yx6btd85vbzb",
      "displayOrder": 0,
      "menuItemId": "js7fz7d7q2wx8tmgy1r43s419985trxw",
      "toppingCategoryId": "viandes"
    },
    {
      "_creationTime": 1777551933008.5134,
      "_id": "jn71270k1mh10ygagqz9w86kjh85tez8",
      "displayOrder": 1,
      "menuItemId": "js7fz7d7q2wx8tmgy1r43s419985trxw",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1777551933008.5137,
      "_id": "jn79jh1svajnhw8rx50hy4n1t185tmhy",
      "displayOrder": 2,
      "menuItemId": "js7fz7d7q2wx8tmgy1r43s419985trxw",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1777551933008.514,
      "_id": "jn701ebtphqff44p44m35vzdrh85t7fe",
      "displayOrder": 0,
      "menuItemId": "js702hkxv40qz4zh2dn8t3g9r985t5fg",
      "toppingCategoryId": "2-viandes"
    },
    {
      "_creationTime": 1777551933008.5142,
      "_id": "jn7ew3j0td6v5yam4r2g96mvf985vje5",
      "displayOrder": 1,
      "menuItemId": "js702hkxv40qz4zh2dn8t3g9r985t5fg",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1777551933008.5144,
      "_id": "jn7660g74q4x26ys6gwq7p4fs985vg7z",
      "displayOrder": 2,
      "menuItemId": "js702hkxv40qz4zh2dn8t3g9r985t5fg",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1777551933008.5146,
      "_id": "jn71b3r4ctz435q2jz7455wbp585v3tn",
      "displayOrder": 0,
      "menuItemId": "js7189d04vj3dc1hceq4t288t985vk6p",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1777551933008.515,
      "_id": "jn71w3v06t7r21q4e8tnq6t1jh85vfyf",
      "displayOrder": 0,
      "menuItemId": "js7bn3z89ms4afm94rse3v6syx85tgmp",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1777551933008.5151,
      "_id": "jn7344ejgp1vf1n08vq85vcqy585vdbc",
      "displayOrder": 0,
      "menuItemId": "js7ej14z7r1d5qeaevvy3rvnvx85tpyc",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1777551933008.5154,
      "_id": "jn74p0qcg5qwcs16179169b8j585t5b0",
      "displayOrder": 0,
      "menuItemId": "js78vnp3e11dv4gtqkxkdtmvrs85taqh",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1777551933008.5156,
      "_id": "jn70haf8dn0vsp0zsjwe9608zs85v45y",
      "displayOrder": 0,
      "menuItemId": "js759s0mp17vydgnedc0xnfaan85vmt1",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1777551933008.5159,
      "_id": "jn7ef71rk18m0fh2c2s3mxyza585vhs7",
      "displayOrder": 0,
      "menuItemId": "js7b246qez8pgttje2cngwhrmh85thcx",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1777551933008.516,
      "_id": "jn732x1p80g22a1xts6wn66j6985vpnj",
      "displayOrder": 0,
      "menuItemId": "js793m8kj2sssc1vd1k8dsjet585tae2",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1777551933008.5164,
      "_id": "jn7cep510pyvwatjd0gzxs5ky185tprd",
      "displayOrder": 1,
      "menuItemId": "js793m8kj2sssc1vd1k8dsjet585tae2",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1777551933008.5166,
      "_id": "jn7fyme7e3szb3rbppyhcphk0185vbnf",
      "displayOrder": 0,
      "menuItemId": "js7c9yqntq405cd4hvdpmvmtfx85v4qc",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1777551933008.5168,
      "_id": "jn72ffkr6cq5mpans4keczxf5n85v1jf",
      "displayOrder": 1,
      "menuItemId": "js7c9yqntq405cd4hvdpmvmtfx85v4qc",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1777551933008.517,
      "_id": "jn7409d925pbzeam0qjeq31tf185vyag",
      "displayOrder": 0,
      "menuItemId": "js71jj5dhkf74cqdm5dayg2t9x85tben",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1777551933008.5173,
      "_id": "jn7fjf82y9mtsbkx2r433mne0n85vkmy",
      "displayOrder": 1,
      "menuItemId": "js71jj5dhkf74cqdm5dayg2t9x85tben",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1777551933008.5176,
      "_id": "jn76389j3xpng7r0qxcgnn8rmh85tyn5",
      "displayOrder": 0,
      "menuItemId": "js7atd4j7dt7jy0pvqj1thgfw985vkxs",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1777551933008.5178,
      "_id": "jn72a0b6qb0a024gr015qsbqys85tfdh",
      "displayOrder": 1,
      "menuItemId": "js7atd4j7dt7jy0pvqj1thgfw985vkxs",
      "toppingCategoryId": "supplements"
    }
  ],
  "menuItems": [
    {
      "_creationTime": 1777551933008.476,
      "_id": "js79w64j5amewk3tspzmmee6ph85vt17",
      "active": true,
      "categories": [
        "pizzas-base-tomate"
      ],
      "description": "Sauce tomate, mozzarella",
      "displayOrder": 0,
      "image": "/pizzas/base-tomate/Margherita.jpg",
      "inStock": true,
      "name": "MARGHERITA",
      "price": 8.5
    },
    {
      "_creationTime": 1777551933008.4763,
      "_id": "js7abq1n5y3s0che5nrstmgtr585tndw",
      "active": true,
      "categories": [
        "pizzas-base-tomate"
      ],
      "description": "Sauce tomate, mozzarella, champignons, jambon",
      "displayOrder": 1,
      "image": "/pizzas/base-tomate/regina.jpg",
      "inStock": true,
      "name": "REGINA",
      "price": 10
    },
    {
      "_creationTime": 1777551933008.4766,
      "_id": "js72z9ygsr4985dr46853pvtrd85v252",
      "active": true,
      "categories": [
        "pizzas-base-tomate"
      ],
      "description": "Sauce tomate, mozzarella, thon, oignon, poivron, olive noire",
      "displayOrder": 2,
      "image": "/pizzas/base-tomate/au-thon.jpg",
      "inStock": true,
      "name": "THON",
      "price": 10
    },
    {
      "_creationTime": 1777551933008.4768,
      "_id": "js7275dmyb6hydwxpqj5h1mg7n85vwz9",
      "active": true,
      "categories": [
        "pizzas-base-tomate"
      ],
      "description": "Sauce tomate, mozzarella, brie, chèvre, gorgonzola",
      "displayOrder": 3,
      "image": "/pizzas/base-tomate/4-fromages.jpg",
      "inStock": true,
      "name": "4 FROMAGES",
      "price": 10
    },
    {
      "_creationTime": 1777551933008.477,
      "_id": "js7e41xxwxr5tyjs0qrc3v3dr985v3t9",
      "active": true,
      "categories": [
        "pizzas-base-tomate"
      ],
      "description": "Sauce tomate, mozzarella, viande hachée, champignons",
      "displayOrder": 4,
      "image": "/pizzas/base-tomate/campione.jpg",
      "inStock": true,
      "name": "CAMPIONE",
      "price": 10
    },
    {
      "_creationTime": 1777551933008.4773,
      "_id": "js71wqenc0nxxjm44zzzrc3vtd85te0m",
      "active": true,
      "categories": [
        "pizzas-base-tomate"
      ],
      "description": "Sauce tomate, mozzarella, merguez, poivron, olives noires, oignon, oeuf",
      "displayOrder": 5,
      "image": "/pizzas/base-tomate/orientale.jpg",
      "inStock": true,
      "name": "ORIENTALE",
      "price": 10
    },
    {
      "_creationTime": 1777551933008.4775,
      "_id": "js72w2ahfxc709r9hty4zm43z185tx1r",
      "active": true,
      "categories": [
        "pizzas-base-tomate"
      ],
      "description": "Sauce tomate, mozzarella, merguez, viande hachée, poulet",
      "displayOrder": 6,
      "image": "/pizzas/base-tomate/royale.jpg",
      "inStock": true,
      "name": "ROYALE",
      "price": 10
    },
    {
      "_creationTime": 1777551933008.4778,
      "_id": "js78y0gkah4gtnksamr2y84nhd85v8jj",
      "active": true,
      "categories": [
        "pizzas-base-tomate"
      ],
      "description": "Sauce tomate, mozzarella, champignons, poivron, artichaut, aubergine, olives noires",
      "displayOrder": 8,
      "image": "/pizzas/base-tomate/vegetarienne.jpg",
      "inStock": true,
      "name": "VÉGÉTARIENNE",
      "price": 10
    },
    {
      "_creationTime": 1777551933008.478,
      "_id": "js70f4hh612ffkf4cvek6xd5dh85twsm",
      "active": true,
      "categories": [
        "pizzas-base-tomate"
      ],
      "description": "Sauce tomate, mozzarella, anchois, câpre, olives noires",
      "displayOrder": 9,
      "image": "/pizzas/base-tomate/napolitaine.jpg",
      "inStock": true,
      "name": "NAPOLITAINE",
      "price": 10
    },
    {
      "_creationTime": 1777551933008.4783,
      "_id": "js72y0vy0bdf7trtp8d0awtxe185t9qt",
      "active": true,
      "categories": [
        "pizzas-base-tomate"
      ],
      "description": "Sauce tomate, mozzarella, jambon, lardons, bacon, pepperoni",
      "displayOrder": 10,
      "image": "/pizzas/base-tomate/4jambons.jpg",
      "inStock": true,
      "name": "4 JAMBONS",
      "price": 11.5
    },
    {
      "_creationTime": 1777551933008.4785,
      "_id": "js744c0c9rn8fzn3r2evm13qm185vr98",
      "active": true,
      "categories": [
        "pizzas-base-tomate"
      ],
      "description": "Sauce tomate, mozzarella, pepperoni, oeuf",
      "displayOrder": 11,
      "image": "/pizzas/base-tomate/pepperoni.jpg",
      "inStock": true,
      "name": "PEPPERONI",
      "price": 10
    },
    {
      "_creationTime": 1777551933008.4788,
      "_id": "js7fsyqrb15atnp25tnhr5bwp985t7ke",
      "active": true,
      "categories": [
        "pizzas-base-tomate"
      ],
      "description": "Sauce tomate, mozzarella, viande kebab, oignon, olives noires",
      "displayOrder": 12,
      "image": "/pizzas/base-tomate/kebab.jpg",
      "inStock": true,
      "name": "KEBAB",
      "price": 10
    },
    {
      "_creationTime": 1777551933008.479,
      "_id": "js75gn99r1n3y82954fpj8pxa985tets",
      "active": true,
      "categories": [
        "pizzas-base-tomate"
      ],
      "description": "Sauce tomate, mozzarella, champignons, jaune d'oeuf, jambon ou viande hachée ou poulet ou thon",
      "displayOrder": 13,
      "image": "/pizzas/base-tomate/calzone.jpg",
      "inStock": false,
      "name": "CALZONE",
      "price": 13.5
    },
    {
      "_creationTime": 1777551933008.4792,
      "_id": "js74ndw8ngjaz77w39jm0vxej185v78b",
      "active": true,
      "categories": [
        "pizzas-base-tomate"
      ],
      "description": "Sauce tomate, mozzarella, cocktail de fruits de mer",
      "displayOrder": 14,
      "image": "/pizzas/base-tomate/fruitsdemer.jpg",
      "inStock": true,
      "name": "FRUITS DE MER",
      "price": 10
    },
    {
      "_creationTime": 1777551933008.4795,
      "_id": "js753af4aymen8g0s9m3xbwywx85v7g7",
      "active": true,
      "categories": [
        "pizzas-base-tomate"
      ],
      "description": "Sauce tomate, mozzarella, jambon, ananas, maïs",
      "displayOrder": 15,
      "image": "/pizzas/base-tomate/hawaienne.jpg",
      "inStock": true,
      "name": "HAWAÏENNE",
      "price": 10
    },
    {
      "_creationTime": 1777551933008.4797,
      "_id": "js7aqpsya18sgq82t4k3k3a39n85tejm",
      "active": true,
      "categories": [
        "pizzas-base-creme"
      ],
      "description": "Base crème, mozzarella, saumon, pomme de terre, oignon",
      "displayOrder": 0,
      "image": "/pizzas/base-creme/saumon.jpg",
      "inStock": true,
      "name": "SAUMON",
      "price": 11.5
    },
    {
      "_creationTime": 1777551933008.48,
      "_id": "js7a0tzr2a1azrnehr9dkhhaqh85v363",
      "active": true,
      "categories": [
        "pizzas-base-creme"
      ],
      "description": "Base crème, mozzarella, chèvre, miel",
      "displayOrder": 1,
      "image": "/pizzas/base-creme/chevre-miel.jpg",
      "inStock": true,
      "name": "CHÈVRE MIEL",
      "price": 10
    },
    {
      "_creationTime": 1777551933008.4802,
      "_id": "js79nwmgyxnwzdk1jh4yc3khp585vt3y",
      "active": true,
      "categories": [
        "pizzas-base-creme"
      ],
      "description": "Base crème, mozzarella, jambon, pomme de terre, raclette",
      "displayOrder": 2,
      "image": "/pizzas/base-creme/raclette.jpg",
      "inStock": true,
      "name": "RACLETTE",
      "price": 10
    },
    {
      "_creationTime": 1777551933008.4805,
      "_id": "js74q4d7a4fk6rpzbqnqzy6gds85vx96",
      "active": true,
      "categories": [
        "pizzas-base-creme"
      ],
      "description": "Base crème, mozzarella, lardons, oignon",
      "displayOrder": 3,
      "image": "/pizzas/base-creme/flamme.jpg",
      "inStock": true,
      "name": "FLAMME",
      "price": 10
    },
    {
      "_creationTime": 1777551933008.4807,
      "_id": "js7cza3eh3vcv6gc31fmdvz2t985vhyr",
      "active": true,
      "categories": [
        "pizzas-base-creme"
      ],
      "description": "Base crème, mozzarella, poulet, oignon, champignons, poivron",
      "displayOrder": 4,
      "image": "/pizzas/base-creme/chicken.jpg",
      "inStock": true,
      "name": "CHICKEN",
      "price": 10
    },
    {
      "_creationTime": 1777551933008.481,
      "_id": "js7es63xtqv650d7m5kqbzcsb985tn57",
      "active": true,
      "categories": [
        "pizzas-base-creme"
      ],
      "description": "Base crème, mozzarella, brie, chèvre, gorgonzola",
      "displayOrder": 5,
      "image": "/pizzas/base-creme/4fromages.jpg",
      "inStock": true,
      "name": "4 FROMAGES",
      "price": 10
    },
    {
      "_creationTime": 1777551933008.4812,
      "_id": "js739aaeq7j2mhztfm2657gs9d85vaa0",
      "active": true,
      "categories": [
        "pizzas-base-creme"
      ],
      "description": "Base crème, viande hachée, pommes de terre, boursin",
      "displayOrder": 6,
      "image": "/pizzas/base-creme/fcmetz.jpg",
      "inStock": true,
      "name": "FC METZ",
      "price": 10
    },
    {
      "_creationTime": 1777551933008.4814,
      "_id": "js7406gtm5wa09gzhepw7pmzwd85tpqn",
      "active": true,
      "categories": [
        "pizzas-base-creme"
      ],
      "description": "Base crème, mozzarella, jambon, pomme de terre, champignons, reblochon, oignons",
      "displayOrder": 7,
      "image": "/pizzas/base-creme/mondo.jpg",
      "inStock": true,
      "name": "MONDO",
      "price": 10
    },
    {
      "_creationTime": 1777551933008.4817,
      "_id": "js77shftwn80ea7q21vhhdkra585thad",
      "active": true,
      "categories": [
        "pizzas-speciales"
      ],
      "description": "Sauce algérienne, mozzarella, viande hachée, pomme de terre, poivron, olives noires",
      "displayOrder": 0,
      "image": "/pizzas/pizzaicon.jpg",
      "inStock": true,
      "name": "ALGÉRIENNE",
      "price": 10
    },
    {
      "_creationTime": 1777551933008.482,
      "_id": "js76g8w71tq876qa1jcyq0x3n585vhca",
      "active": true,
      "categories": [
        "pizzas-speciales"
      ],
      "description": "Sauce curry, mozzarella, poulet, oignon, poivron",
      "displayOrder": 1,
      "image": "/pizzas/pizzaicon.jpg",
      "inStock": true,
      "name": "INDIENNE",
      "price": 10
    },
    {
      "_creationTime": 1777551933008.4822,
      "_id": "js7bea2y0rzbq2at41nke4tcr585v4kf",
      "active": true,
      "categories": [
        "pizzas-speciales"
      ],
      "description": "Sauce andalouse, mozzarella, poulet, oignon, poivron, chèvre",
      "displayOrder": 2,
      "image": "/pizzas/pizzaicon.jpg",
      "inStock": true,
      "name": "ANDALOUSE",
      "price": 10
    },
    {
      "_creationTime": 1777551933008.4824,
      "_id": "js7afqjaheervy5rk7r7zdsr4n85vr8b",
      "active": true,
      "categories": [
        "paninis"
      ],
      "description": "Sauce tomate ou crème fraîche + boisson",
      "displayOrder": 0,
      "image": "",
      "inStock": false,
      "name": "PANINI MERGUEZ",
      "price": 7.5
    },
    {
      "_creationTime": 1777551933008.4827,
      "_id": "js7df4ndmhr4pqm9jz5rpchsan85v6ps",
      "active": true,
      "categories": [
        "paninis"
      ],
      "description": "Sauce tomate ou crème fraiche + boisson",
      "displayOrder": 1,
      "image": "",
      "inStock": false,
      "name": "POULET",
      "price": 7.5
    },
    {
      "_creationTime": 1777551933008.483,
      "_id": "js70w40r3825maccj5e5w1jc5n85vfpj",
      "active": true,
      "categories": [
        "paninis"
      ],
      "description": "Sauce tomate ou crème fraiche + boisson",
      "displayOrder": 2,
      "image": "",
      "inStock": false,
      "name": "VIANDE HACHÉE",
      "price": 7.5
    },
    {
      "_creationTime": 1777551933008.4832,
      "_id": "js7577zpzejze0qb4the74w2qx85tz1f",
      "active": true,
      "categories": [
        "paninis"
      ],
      "description": "Sauce tomate ou crème fraiche + boisson",
      "displayOrder": 3,
      "image": "",
      "inStock": false,
      "name": "SAUMON",
      "price": 7.5
    },
    {
      "_creationTime": 1777551933008.4834,
      "_id": "js75n3cv0aqc8s4bh0wwtc9tcd85vmhg",
      "active": true,
      "categories": [
        "paninis"
      ],
      "description": "Sauce tomate ou crème fraiche + boisson",
      "displayOrder": 4,
      "image": "",
      "inStock": false,
      "name": "4 FROMAGES",
      "price": 7.5
    },
    {
      "_creationTime": 1777551933008.4836,
      "_id": "js7e53b5wqgkn3p05d342t1bh185v05b",
      "active": true,
      "categories": [
        "paninis"
      ],
      "description": "Sauce tomate ou crème fraiche + boisson",
      "displayOrder": 5,
      "image": "",
      "inStock": false,
      "name": "THON",
      "price": 7.5
    },
    {
      "_creationTime": 1777551933008.484,
      "_id": "js7fs3ewptbhczy5d67r6tew8x85v93y",
      "active": true,
      "categories": [
        "burgers"
      ],
      "description": "Steak, Cheddar, Crudités + Boisson 33cl",
      "displayOrder": 0,
      "image": "",
      "inStock": false,
      "name": "CHEESEBURGER",
      "price": 6.5
    },
    {
      "_creationTime": 1777551933008.4841,
      "_id": "js70v78fcwr48pqtewz3x53pan85vjyt",
      "active": true,
      "categories": [
        "burgers"
      ],
      "description": "2 Steaks, 2 Cheddars, Crudités + Boisson 33cl",
      "displayOrder": 1,
      "image": "",
      "inStock": false,
      "name": "DOBLE CHEESE",
      "price": 8.5
    },
    {
      "_creationTime": 1777551933008.4844,
      "_id": "js73zp2qp2bgbkg7rnhhw3m16d85ta0b",
      "active": true,
      "categories": [
        "burgers"
      ],
      "description": "Galette de poulet, galette de pomme de terre et 2 cheddars, Crudités + Boisson 33cl",
      "displayOrder": 2,
      "image": "",
      "inStock": false,
      "name": "LE CHICKEN",
      "price": 7.5
    },
    {
      "_creationTime": 1777551933008.4846,
      "_id": "js7fz7d7q2wx8tmgy1r43s419985trxw",
      "active": true,
      "categories": [
        "tacos"
      ],
      "description": "1 Viande au choix, servi with a drink 33cl",
      "displayOrder": 0,
      "image": "",
      "inStock": true,
      "name": "TACOS 1 VIANDE",
      "price": 7
    },
    {
      "_creationTime": 1777551933008.4849,
      "_id": "js702hkxv40qz4zh2dn8t3g9r985t5fg",
      "active": true,
      "categories": [
        "tacos"
      ],
      "description": "2 Viandes au choix, servi with a drink 33cl",
      "displayOrder": 1,
      "image": "/tacos2.jpeg",
      "inStock": true,
      "name": "TACOS 2 VIANDES",
      "price": 9
    },
    {
      "_creationTime": 1777551933008.485,
      "_id": "js7189d04vj3dc1hceq4t288t985vk6p",
      "active": true,
      "categories": [
        "tex-mex"
      ],
      "description": "",
      "displayOrder": 0,
      "image": "/tex-mex/frites.jpg",
      "inStock": true,
      "name": "FRITES",
      "price": 3.5
    },
    {
      "_creationTime": 1777551933008.4854,
      "_id": "js7bn3z89ms4afm94rse3v6syx85tgmp",
      "active": true,
      "categories": [
        "tex-mex"
      ],
      "description": "",
      "displayOrder": 1,
      "image": "/tex-mex/potatoes.jpg",
      "inStock": true,
      "name": "POTATOES",
      "price": 3.5
    },
    {
      "_creationTime": 1777551933008.4856,
      "_id": "js7ej14z7r1d5qeaevvy3rvnvx85tpyc",
      "active": true,
      "categories": [
        "tex-mex"
      ],
      "description": "Servi avec frites ou potatoes",
      "displayOrder": 2,
      "image": "/tex-mex/nuggets.jpg",
      "inStock": true,
      "name": "NUGGETS X8",
      "price": 10
    },
    {
      "_creationTime": 1777551933008.4858,
      "_id": "js78vnp3e11dv4gtqkxkdtmvrs85taqh",
      "active": true,
      "categories": [
        "tex-mex"
      ],
      "description": "Servi avec frites ou potatoes",
      "displayOrder": 3,
      "image": "/tex-mex/nuggets.jpg",
      "inStock": true,
      "name": "NUGGETS X12",
      "price": 13
    },
    {
      "_creationTime": 1777551933008.486,
      "_id": "js759s0mp17vydgnedc0xnfaan85vmt1",
      "active": true,
      "categories": [
        "tex-mex"
      ],
      "description": "Servi avec frites ou potatoes",
      "displayOrder": 4,
      "image": "/tex-mex/wings.jpg",
      "inStock": true,
      "name": "CHICKEN WINGS X10",
      "price": 10
    },
    {
      "_creationTime": 1777551933008.4863,
      "_id": "js7b246qez8pgttje2cngwhrmh85thcx",
      "active": true,
      "categories": [
        "tex-mex"
      ],
      "description": "Servi avec frites ou potatoes",
      "displayOrder": 5,
      "image": "/tex-mex/wings.jpg",
      "inStock": true,
      "name": "CHICKEN WINGS X12",
      "price": 13
    },
    {
      "_creationTime": 1777551933008.4866,
      "_id": "js793m8kj2sssc1vd1k8dsjet585tae2",
      "active": true,
      "categories": [
        "salades"
      ],
      "description": "Tomates cerises, saumon, avocat, oignon, pomme de terre",
      "displayOrder": 0,
      "image": "",
      "inStock": false,
      "name": "SAUMON",
      "price": 7.5
    },
    {
      "_creationTime": 1777551933008.4868,
      "_id": "js7c9yqntq405cd4hvdpmvmtfx85v4qc",
      "active": true,
      "categories": [
        "salades"
      ],
      "description": "Tomates cerises, thon, mais, olives noires, oeuf dur",
      "displayOrder": 1,
      "image": "",
      "inStock": false,
      "name": "THON",
      "price": 7.5
    },
    {
      "_creationTime": 1777551933008.487,
      "_id": "js71jj5dhkf74cqdm5dayg2t9x85tben",
      "active": true,
      "categories": [
        "salades"
      ],
      "description": "Tomates cerises, lardon, chèvre chaud",
      "displayOrder": 2,
      "image": "",
      "inStock": false,
      "name": "CHÈVRE CHAUD",
      "price": 7.5
    },
    {
      "_creationTime": 1777551933008.4873,
      "_id": "js7atd4j7dt7jy0pvqj1thgfw985vkxs",
      "active": true,
      "categories": [
        "salades"
      ],
      "description": "Tomates cerises, poulet, pomme de terre, olives noires",
      "displayOrder": 3,
      "image": "/salade-poulet-min.jpg",
      "inStock": false,
      "name": "FERMIÈRE",
      "price": 7.5
    },
    {
      "_creationTime": 1777551933008.4875,
      "_id": "js71af3wf8ng0xa269dyfdn32185v5se",
      "active": true,
      "categories": [
        "desserts"
      ],
      "description": "",
      "displayOrder": 0,
      "image": "",
      "name": "TARTE AU DAIM",
      "price": 4
    },
    {
      "_creationTime": 1777551933008.4878,
      "_id": "js78hy111dm07tyw1kvn2t4exx85va0v",
      "active": true,
      "categories": [
        "desserts"
      ],
      "description": "",
      "displayOrder": 1,
      "image": "/tiramisu.jpeg",
      "name": "TIRAMISU",
      "price": 4
    },
    {
      "_creationTime": 1777551933008.488,
      "_id": "js7b4sn258k5t57hf7mfbq5nyx85vpxt",
      "active": true,
      "categories": [
        "desserts"
      ],
      "description": "",
      "displayOrder": 2,
      "image": "",
      "name": "BROWNIES",
      "price": 4
    },
    {
      "_creationTime": 1777551933008.4883,
      "_id": "js75a3cynbcg9rvgm6g557q6vs85tr6j",
      "active": true,
      "categories": [
        "desserts"
      ],
      "description": "",
      "displayOrder": 3,
      "image": "",
      "name": "TARTE AU CITRON",
      "price": 4
    },
    {
      "_creationTime": 1777551933008.4885,
      "_id": "js7bfr803pgzeybz6cc9q1qkdn85v8nw",
      "active": true,
      "categories": [
        "desserts"
      ],
      "description": "",
      "displayOrder": 4,
      "image": "",
      "name": "BEN & JERRY'S 100 ml",
      "price": 3
    },
    {
      "_creationTime": 1777551933008.4888,
      "_id": "js7eya0vp4q9es8d31d0gppgfn85vk31",
      "active": true,
      "categories": [
        "desserts"
      ],
      "description": "",
      "displayOrder": 5,
      "image": "",
      "name": "BEN & JERRY'S 500 ml",
      "price": 6
    },
    {
      "_creationTime": 1777551933008.489,
      "_id": "js77tqmgnzsgm60nxf00h2j76585v2km",
      "active": true,
      "categories": [
        "boissons"
      ],
      "description": "",
      "displayOrder": 100,
      "image": "",
      "inStock": true,
      "name": "Fanta Orange 33cl",
      "price": 1.8
    },
    {
      "_creationTime": 1777551933008.4893,
      "_id": "js7er99qezjgkk6e0hjdn7rvj185ts1k",
      "active": true,
      "categories": [
        "boissons"
      ],
      "description": "",
      "displayOrder": 101,
      "image": "",
      "inStock": true,
      "name": "Coca-Cola Cherry 33cl",
      "popular": true,
      "price": 1.8
    },
    {
      "_creationTime": 1777551933008.4895,
      "_id": "js77sfx4mzz05hm9re05fdtkpn85vft6",
      "active": true,
      "categories": [
        "boissons"
      ],
      "description": "",
      "displayOrder": 102,
      "image": "",
      "inStock": true,
      "name": "Orangina 33cl",
      "price": 1.8
    },
    {
      "_creationTime": 1777551933008.4897,
      "_id": "js78xe56fs0c0c2pbpfcdsx2vx85vam5",
      "active": true,
      "categories": [
        "boissons"
      ],
      "description": "",
      "displayOrder": 103,
      "image": "",
      "inStock": true,
      "name": "Perrier 33cl",
      "price": 1.8
    },
    {
      "_creationTime": 1777551933008.49,
      "_id": "js78kbscfmpgds6pa0tcafgcn185v6qx",
      "active": true,
      "categories": [
        "boissons"
      ],
      "description": "",
      "displayOrder": 104,
      "image": "",
      "inStock": true,
      "name": "7 Up 33cl",
      "price": 1.8
    },
    {
      "_creationTime": 1777551933008.4902,
      "_id": "js7818c22xpcnqvgabcg7kvr6x85tz7j",
      "active": true,
      "categories": [
        "boissons"
      ],
      "description": "",
      "displayOrder": 105,
      "image": "",
      "inStock": true,
      "name": "Schweppes Agrumes 33cl",
      "price": 1.8
    },
    {
      "_creationTime": 1777551933008.4905,
      "_id": "js78zk8mj9nr6ygjbdaz22ayk985vbvv",
      "active": true,
      "categories": [
        "boissons"
      ],
      "description": "",
      "displayOrder": 106,
      "image": "",
      "inStock": true,
      "name": "Sprite 33cl",
      "price": 1.8
    },
    {
      "_creationTime": 1777551933008.4907,
      "_id": "js763gh9b241kg4z9p2z10nn7h85tth2",
      "active": true,
      "categories": [
        "boissons"
      ],
      "description": "",
      "displayOrder": 107,
      "image": "",
      "inStock": true,
      "name": "Red Bull 25cl",
      "price": 2.5
    },
    {
      "_creationTime": 1777551933008.491,
      "_id": "js70ksr69fwevrqpwaqe0v1sgs85taq0",
      "active": true,
      "categories": [
        "boissons"
      ],
      "description": "",
      "displayOrder": 108,
      "image": "",
      "inStock": true,
      "name": "Coca Cola 1.5L",
      "popular": true,
      "price": 3.5
    },
    {
      "_creationTime": 1777551933008.4912,
      "_id": "js7cqmzh9hfhrd7wnpp3jkjgp985vyd8",
      "active": true,
      "categories": [
        "boissons"
      ],
      "description": "",
      "displayOrder": 109,
      "image": "",
      "inStock": true,
      "name": "Fanta Orange 1.5L",
      "price": 3.5
    },
    {
      "_creationTime": 1777551933008.4915,
      "_id": "js7fyapfqjk27gmmdjbrww3ax185vdvh",
      "active": true,
      "categories": [
        "boissons"
      ],
      "description": "",
      "displayOrder": 110,
      "image": "",
      "inStock": true,
      "name": "Monster Energy 50cl",
      "price": 2.5
    },
    {
      "_creationTime": 1777551933008.4917,
      "_id": "js73epye1tar5142mw5m55bf9s85trk2",
      "active": true,
      "categories": [
        "boissons"
      ],
      "description": "",
      "displayOrder": 111,
      "image": "",
      "inStock": true,
      "name": "Coca-Cola 33cl",
      "popular": true,
      "price": 1.8
    },
    {
      "_creationTime": 1777551933008.492,
      "_id": "js74xwv5a76v6sjmg8bvjzwcmx85vhjv",
      "active": true,
      "categories": [
        "boissons"
      ],
      "description": "",
      "displayOrder": 112,
      "image": "",
      "inStock": true,
      "name": "Coca-Cola Zéro 33cl",
      "popular": true,
      "price": 1.8
    },
    {
      "_creationTime": 1777551933008.4922,
      "_id": "js7ae8ck9bf6y7pdc21fjyxatd85tgaw",
      "active": true,
      "categories": [
        "boissons"
      ],
      "description": "",
      "displayOrder": 113,
      "image": "",
      "inStock": true,
      "name": "Ice Tea 33cl",
      "price": 1.8
    },
    {
      "_creationTime": 1777551933008.4924,
      "_id": "js75bz9esbgyt24ybskwe3sbqd85vm6c",
      "active": true,
      "categories": [
        "boissons"
      ],
      "description": "",
      "displayOrder": 114,
      "image": "",
      "inStock": true,
      "name": "Oasis 33cl",
      "price": 1.8
    },
    {
      "_creationTime": 1777551933008.4927,
      "_id": "js7b70rjk8k8vmfd0fvrc8fqy185tv06",
      "active": true,
      "categories": [
        "boissons"
      ],
      "description": "",
      "displayOrder": 115,
      "image": "",
      "inStock": true,
      "name": "Eau Minérale 33cl",
      "price": 1.8
    },
    {
      "_creationTime": 1777551933008.493,
      "_id": "js774b52f2d7c8hpwce0nnwhyh85t5je",
      "active": true,
      "categories": [
        "boissons"
      ],
      "description": "",
      "displayOrder": 116,
      "image": "",
      "inStock": true,
      "name": "Dada 33cl",
      "price": 1.8
    },
    {
      "_creationTime": 1777551933008.4932,
      "_id": "js7a8bz9d6aca788tg6k7ztwg985t9dt",
      "active": true,
      "categories": [
        "boissons"
      ],
      "description": "",
      "displayOrder": 117,
      "image": "",
      "inStock": true,
      "name": "Ice Tea 1.5L",
      "price": 3.5
    },
    {
      "_creationTime": 1777551933008.4934,
      "_id": "js7c03n0qdyr9mqdx39azvww0n85twrv",
      "active": true,
      "categories": [
        "boissons"
      ],
      "description": "",
      "displayOrder": 118,
      "image": "",
      "inStock": true,
      "name": "Oasis 2L",
      "price": 3.5
    },
    {
      "_creationTime": 1777551933008.4937,
      "_id": "js78jmy4vr7r6bms0j0ygp8z8s85v4y6",
      "active": true,
      "categories": [
        "boissons"
      ],
      "description": "",
      "displayOrder": 0,
      "image": "",
      "inStock": true,
      "name": "Coca Cola Zéro 1.5L",
      "price": 3.5
    }
  ],
  "restaurantInfo": [
    {
      "_creationTime": 1777551933008.518,
      "_id": "k174grr1py4qcbwrt5rc95598585tfx8",
      "address": "20 Rue Saint-Pierre 57000 Metz",
      "defaultDeliveryFee": 0,
      "deliveryEnabled": true,
      "email": "contact@mondopizza57.fr",
      "freeDeliveryThreshold": 0,
      "galleryEnabled": false,
      "hours": [
        {
          "day": "Lundi",
          "time": "11h00 - 14h00 et 17h30 - 23h00"
        },
        {
          "day": "Mardi",
          "time": "11h00 - 14h00 et 17h30 - 23h00"
        },
        {
          "day": "Mercredi",
          "time": "11h00 - 14h00 et 17h30 - 23h00"
        },
        {
          "day": "Jeudi",
          "time": "11h00 - 14h00 et 17h30 - 23h00"
        },
        {
          "day": "Vendredi",
          "time": "11h00 - 14h00 et 17h30 - 23h00"
        },
        {
          "day": "Samedi",
          "time": "17h30 - 23h00"
        },
        {
          "day": "Dimanche",
          "time": "17h30 - 23h00"
        }
      ],
      "key": "main",
      "minimumAdvanceNotice": 30,
      "phone": "03 87 38 09 45",
      "pickupEnabled": true,
      "reviewsEnabled": true,
      "socialLinks": {
        "facebook": "",
        "instagram": "",
        "twitter": ""
      }
    }
  ],
  "reviews": [
    {
      "_creationTime": 1777551933008.5183,
      "_id": "k5729gbtfeawj37b1xsny4t7v985vp51",
      "active": true,
      "comment": "Excellente expérience le patron (ou employer ) très gentil et poli et service super rapide et très très bonne pizza !!!",
      "date": "12 mars 2026",
      "name": "Alonzo",
      "rating": 5
    },
    {
      "_creationTime": 1777551933008.5186,
      "_id": "k576jz1zxpbap3qev3bppdbbhh85ta03",
      "active": true,
      "comment": "Enfin une bonne pizzeria sur Metz avec des produits frais (ce qui est plus que rare de nos jours) et de la pâte faite maison !\nL'accueil est super, les gars sont très sympas et ça se voit qu'il aiment ce qu'ils font.\nEnviron 15min d'attente pour notre commande, au top 👌\nAllez-y, vous ne serez pas déçu !",
      "date": "04 avril 2026",
      "name": "Laura",
      "rating": 5
    },
    {
      "_creationTime": 1777551933008.5188,
      "_id": "k573dsq2fktvxkse17fyfxaxv585ve2w",
      "active": true,
      "comment": "Meilleures pizza de metz accueil merveilleux, produits de qualités, goût et saveurs italienne. Merci de ramener cette spécialité italienne sur Metz sablon et de le partager avec nous un vrai régal avec des offres familiales à petit prix! Il y a des crêpes salées, sucrées, banane, fraises et framboise avec tout les goûts. Les dada enfin je sais où vous trouver !!!! Rien à dire vous êtes les meilleurs merci les italiens tounsi un grand cœur pour vous .",
      "date": "30 avril 2025",
      "name": "Naim",
      "rating": 5
    },
    {
      "_creationTime": 1777551933008.519,
      "_id": "k5709817c36g2j7v3e6hrg16gd85tzcn",
      "active": true,
      "comment": "La meilleure pizza de Metz\nDe super prix pour de super pizza\nEt surtout des Livreurs au Top\nMerciii Mondo Pizza",
      "date": "30 mars 2025",
      "name": "Anita",
      "rating": 5
    }
  ],
  "toppingCategories": [
    {
      "_creationTime": 1777551933008.4644,
      "_id": "k97b1wbtr2p80p6q02xhx11sss85tbyc",
      "active": true,
      "categoryId": "sauces",
      "displayOrder": 3,
      "maxSelection": 3,
      "minSelection": 0,
      "name": "Sauces"
    },
    {
      "_creationTime": 1777551933008.4646,
      "_id": "k97abcbhc6x6v1fmnspr9wvkjn85vxy3",
      "active": true,
      "categoryId": "crudites",
      "displayOrder": 4,
      "maxSelection": 4,
      "minSelection": 0,
      "name": "Crudités"
    },
    {
      "_creationTime": 1777551933008.4648,
      "_id": "k979zn4bj97xhgmkyyk8vny59585vc6c",
      "active": true,
      "categoryId": "supplements",
      "displayOrder": 5,
      "maxSelection": 10,
      "minSelection": 0,
      "name": "Suppléments"
    },
    {
      "_creationTime": 1777551933008.465,
      "_id": "k97dzawbs214wbx5wq3bf5g4fx85v492",
      "active": true,
      "categoryId": "viandes",
      "displayOrder": 1,
      "maxSelection": 1,
      "minSelection": 1,
      "name": "1 Viandes"
    },
    {
      "_creationTime": 1777551933008.4653,
      "_id": "k9717v689v9bkeh0anczxwmhgs85vh5k",
      "active": true,
      "categoryId": "2-viandes",
      "displayOrder": 2,
      "maxSelection": 2,
      "minSelection": 1,
      "name": "2 Vaindes"
    },
    {
      "_creationTime": 1777551933008.4656,
      "_id": "k9746625hb6m51b62d695x8ad985t4z0",
      "active": true,
      "categoryId": "taille",
      "displayOrder": 0,
      "maxSelection": 1,
      "minSelection": 0,
      "name": "Taille Pizza"
    }
  ],
  "toppings": [
    {
      "_creationTime": 1777551933008.4658,
      "_id": "kd794tc64ge74tzztew6esqwbn85vs7a",
      "active": true,
      "categoryId": "sauces",
      "displayOrder": 0,
      "name": "Sauce Blanche",
      "price": 0,
      "toppingId": "sauce-blanche"
    },
    {
      "_creationTime": 1777551933008.466,
      "_id": "kd74c4mnegb8p13fqvd2yjeddn85tnc1",
      "active": true,
      "categoryId": "sauces",
      "displayOrder": 1,
      "name": "Sauce Andalouse",
      "price": 0,
      "toppingId": "sauce-andalouse"
    },
    {
      "_creationTime": 1777551933008.4663,
      "_id": "kd74vy3n9qwc95yahcmpg2eb7985vs5j",
      "active": true,
      "categoryId": "crudites",
      "displayOrder": 11,
      "name": "Salade",
      "price": 0,
      "toppingId": "salade"
    },
    {
      "_creationTime": 1777551933008.4666,
      "_id": "kd7d31cr56sg8r590vkz9md0jx85tnh5",
      "active": true,
      "categoryId": "crudites",
      "displayOrder": 12,
      "name": "Tomate",
      "price": 0,
      "toppingId": "tomate"
    },
    {
      "_creationTime": 1777551933008.4668,
      "_id": "kd75x2netpr55xnj6kwye06sg585t6e0",
      "active": true,
      "categoryId": "crudites",
      "displayOrder": 13,
      "name": "Oignon",
      "price": 0,
      "toppingId": "oignon"
    },
    {
      "_creationTime": 1777551933008.467,
      "_id": "kd7afckkppj9k0pzh350h0xczs85tf67",
      "active": true,
      "categoryId": "crudites",
      "displayOrder": 14,
      "name": "Chou Rouge",
      "price": 0,
      "toppingId": "chou-rouge"
    },
    {
      "_creationTime": 1777551933008.4673,
      "_id": "kd7d4pzen2f4ghy5nkjfgdv9g985vxfe",
      "active": true,
      "categoryId": "crudites",
      "displayOrder": 15,
      "name": "Maïs",
      "price": 0,
      "toppingId": "mais"
    },
    {
      "_creationTime": 1777551933008.4675,
      "_id": "kd7e6d41h3rmnc1akmt7nm61xs85v595",
      "active": true,
      "categoryId": "crudites",
      "displayOrder": 16,
      "name": "Olives Noires",
      "price": 0,
      "toppingId": "olives-noires"
    },
    {
      "_creationTime": 1777551933008.4678,
      "_id": "kd7en0awbqec1n9ev5440966k185tf2n",
      "active": true,
      "categoryId": "supplements",
      "displayOrder": 17,
      "name": "Extra Mozzarella",
      "price": 1.5,
      "toppingId": "mozzarella-extra"
    },
    {
      "_creationTime": 1777551933008.468,
      "_id": "kd78cb2r8g37c9awegzar8j7z985v8jz",
      "active": true,
      "categoryId": "supplements",
      "displayOrder": 18,
      "name": "Cheddar",
      "price": 1,
      "toppingId": "cheddar"
    },
    {
      "_creationTime": 1777551933008.4683,
      "_id": "kd70r558r12tq38hs04mw08s1585vvkm",
      "active": true,
      "categoryId": "supplements",
      "displayOrder": 19,
      "name": "Feta",
      "price": 1.5,
      "toppingId": "feta"
    },
    {
      "_creationTime": 1777551933008.4685,
      "_id": "kd7fb3s50k7ky7rzdy48qwk6dn85vnnx",
      "active": true,
      "categoryId": "supplements",
      "displayOrder": 20,
      "name": "Chèvre",
      "price": 1.5,
      "toppingId": "chevre"
    },
    {
      "_creationTime": 1777551933008.4688,
      "_id": "kd7an26csmzrht00gshk08v55185vpep",
      "active": true,
      "categoryId": "supplements",
      "displayOrder": 21,
      "name": "Brie",
      "price": 1.5,
      "toppingId": "brie"
    },
    {
      "_creationTime": 1777551933008.469,
      "_id": "kd721n36d3t2kx9j22717w2xjx85tccx",
      "active": true,
      "categoryId": "supplements",
      "displayOrder": 22,
      "name": "Gorgonzola",
      "price": 1.5,
      "toppingId": "gorgonzola"
    },
    {
      "_creationTime": 1777551933008.4692,
      "_id": "kd72qegv5gnyecrng4mzwjb2an85vh0r",
      "active": true,
      "categoryId": "supplements",
      "displayOrder": 23,
      "name": "Raclette",
      "price": 1.5,
      "toppingId": "raclette"
    },
    {
      "_creationTime": 1777551933008.4695,
      "_id": "kd71c24j0vaj92yh4gd8fz9cex85t1m8",
      "active": true,
      "categoryId": "supplements",
      "displayOrder": 24,
      "name": "Reblochon",
      "price": 1.5,
      "toppingId": "reblochon"
    },
    {
      "_creationTime": 1777551933008.4697,
      "_id": "kd75rsnavww4gkrfhpqmy4sb8d85vjwy",
      "active": true,
      "categoryId": "supplements",
      "displayOrder": 25,
      "name": "Champignons",
      "price": 1,
      "toppingId": "champignons"
    },
    {
      "_creationTime": 1777551933008.47,
      "_id": "kd74nak85jh8jqx6xj1m8kj31s85v873",
      "active": true,
      "categoryId": "supplements",
      "displayOrder": 26,
      "name": "Poivrons",
      "price": 1,
      "toppingId": "poivrons"
    },
    {
      "_creationTime": 1777551933008.4702,
      "_id": "kd7dvm05n1a7zw01e684jeexn185vf34",
      "active": true,
      "categoryId": "supplements",
      "displayOrder": 27,
      "name": "Oignons",
      "price": 1,
      "toppingId": "oignons-pizza"
    },
    {
      "_creationTime": 1777551933008.4705,
      "_id": "kd76azvh1hgg319jdkr0tz1jj585ve2c",
      "active": true,
      "categoryId": "supplements",
      "displayOrder": 28,
      "name": "Olives",
      "price": 1,
      "toppingId": "olives-pizza"
    },
    {
      "_creationTime": 1777551933008.4707,
      "_id": "kd715168td0dcmxd6qh9xh5q1985t5vh",
      "active": true,
      "categoryId": "supplements",
      "displayOrder": 29,
      "name": "Oeuf",
      "price": 1,
      "toppingId": "oeuf"
    },
    {
      "_creationTime": 1777551933008.471,
      "_id": "kd755ty9jpny61jwkcqvv7hg8s85vf7s",
      "active": true,
      "categoryId": "supplements",
      "displayOrder": 30,
      "name": "Pomme de Terre",
      "price": 1,
      "toppingId": "pomme-de-terre"
    },
    {
      "_creationTime": 1777551933008.4712,
      "_id": "kd74v1bybje1msf3q8hza5mcwd85v5v1",
      "active": true,
      "categoryId": "supplements",
      "displayOrder": 31,
      "name": "Ananas",
      "price": 1,
      "toppingId": "ananas"
    },
    {
      "_creationTime": 1777551933008.4714,
      "_id": "kd7fytsv36h99yf0k8rgbktzt985tcwn",
      "active": true,
      "categoryId": "supplements",
      "displayOrder": 32,
      "name": "Miel",
      "price": 0.5,
      "toppingId": "miel"
    },
    {
      "_creationTime": 1777551933008.4717,
      "_id": "kd7cnab5x5vcakre14syzf7hzd85vghe",
      "active": true,
      "categoryId": "viandes",
      "displayOrder": 34,
      "name": "Escalope de Poulet",
      "price": 0,
      "toppingId": "poulet"
    },
    {
      "_creationTime": 1777551933008.472,
      "_id": "kd7a4zg8qwf9yrdb3cxereg0vd85v739",
      "active": true,
      "categoryId": "viandes",
      "displayOrder": 33,
      "name": "Steak",
      "price": 0,
      "toppingId": "viande-hachee"
    },
    {
      "_creationTime": 1777551933008.4722,
      "_id": "kd7ftgqkmwbbpa7xgcnbyj5ds585v3ss",
      "active": true,
      "categoryId": "viandes",
      "displayOrder": 35,
      "name": "Poulet Tandoori",
      "price": 0,
      "toppingId": "merguez"
    },
    {
      "_creationTime": 1777551933008.4724,
      "_id": "kd7d6568t971e9h23hnt49kks985tm6v",
      "active": true,
      "categoryId": "viandes",
      "displayOrder": 36,
      "name": "Chicken Chika",
      "price": 0,
      "toppingId": "kebab-topping"
    },
    {
      "_creationTime": 1777551933008.4727,
      "_id": "kd71168csh0zxm5t3c1b0pk4v185tgwc",
      "active": true,
      "categoryId": "viandes",
      "displayOrder": 37,
      "name": "Viande Kebab",
      "price": 0,
      "toppingId": "jambon"
    },
    {
      "_creationTime": 1777551933008.473,
      "_id": "kd7akkd0kmfvekwn16r7qb6fes85ta7n",
      "active": true,
      "categoryId": "viandes",
      "displayOrder": 38,
      "name": "Cordon Bleu",
      "price": 0,
      "toppingId": "lardons"
    },
    {
      "_creationTime": 1777551933008.4731,
      "_id": "kd7aj1g91vspecc2fpmdbc9x0185tmb3",
      "active": true,
      "categoryId": "viandes",
      "displayOrder": 39,
      "name": "Tenders",
      "price": 0,
      "toppingId": "bacon"
    },
    {
      "_creationTime": 1777551933008.4734,
      "_id": "kd7b4kh66gmq7hqx33nfpkxvjx85vv9x",
      "active": true,
      "categoryId": "viandes",
      "displayOrder": 40,
      "name": "Nuggets",
      "price": 0,
      "toppingId": "pepperoni"
    },
    {
      "_creationTime": 1777551933008.4736,
      "_id": "kd7f6cxrxz2d5whsmz1s1epra185t07v",
      "active": true,
      "categoryId": "2-viandes",
      "displayOrder": 32,
      "name": "Steak",
      "price": 0,
      "toppingId": "topping-1777547095472"
    },
    {
      "_creationTime": 1777551933008.4739,
      "_id": "kd7bnzdm5k0q0hz8cq6fesqj5s85tesr",
      "active": true,
      "categoryId": "2-viandes",
      "displayOrder": 33,
      "name": "Escalope de Poulet",
      "price": 0,
      "toppingId": "topping-1777547112484"
    },
    {
      "_creationTime": 1777551933008.474,
      "_id": "kd7btrbjd3cvm02abaq4v8djv985vvdk",
      "active": true,
      "categoryId": "2-viandes",
      "displayOrder": 34,
      "name": "Poulet Tandoori",
      "price": 0,
      "toppingId": "topping-1777547122429"
    },
    {
      "_creationTime": 1777551933008.4744,
      "_id": "kd74vty2qftdmj3q5ac7apep9s85v363",
      "active": true,
      "categoryId": "2-viandes",
      "displayOrder": 35,
      "name": "Chicken Chika",
      "price": 0,
      "toppingId": "topping-1777547130221"
    },
    {
      "_creationTime": 1777551933008.4746,
      "_id": "kd73d65c18509wm8mxaesk10ad85vj54",
      "active": true,
      "categoryId": "2-viandes",
      "displayOrder": 36,
      "name": "Viande Kebab",
      "price": 0,
      "toppingId": "topping-1777547142493"
    },
    {
      "_creationTime": 1777551933008.4749,
      "_id": "kd7bsx6gxrw3q8xrde5jv1m0c985tqc9",
      "active": true,
      "categoryId": "2-viandes",
      "displayOrder": 37,
      "name": "Cordon Bleu",
      "price": 0,
      "toppingId": "topping-1777547159751"
    },
    {
      "_creationTime": 1777551933008.475,
      "_id": "kd7drftbnae7g6ewgwmaq6rdsn85tzk0",
      "active": true,
      "categoryId": "2-viandes",
      "displayOrder": 38,
      "name": "Tenders",
      "price": 0,
      "toppingId": "topping-1777547171719"
    },
    {
      "_creationTime": 1777551933008.4753,
      "_id": "kd7d7e918bvt05q7grrn681efx85vw7x",
      "active": true,
      "categoryId": "2-viandes",
      "displayOrder": 39,
      "name": "Nuggets",
      "price": 0,
      "toppingId": "topping-1777547187042"
    },
    {
      "_creationTime": 1777551933008.4756,
      "_id": "kd78x8s7f0qczm36nrqe8v4ban85v9ec",
      "active": true,
      "categoryId": "taille",
      "displayOrder": 41,
      "name": "33 CM",
      "price": 3,
      "toppingId": "topping-1777548068398"
    },
    {
      "_creationTime": 1777551933008.4758,
      "_id": "kd73te8spanjrjjv13902wwjvx85t4p7",
      "active": true,
      "categoryId": "taille",
      "displayOrder": 40,
      "name": "29 CM",
      "price": 0,
      "toppingId": "topping-1777548084889"
    }
  ]
};
